name: Release

on:
  pull_request:
      branches: [ "main" ]
  push:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: Install Prerequisites
        run: |
          sudo apt-get install libpcap-dev 
      - name: Build
        run: CGO_ENABLED=1 go build -o sherlock -v ./...
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: sherlock
          path: sherlock
